# Generated by Django 5.1 on 2025-05-05 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoSolicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Cargo')),
            ],
            options={
                'verbose_name': 'Cargo del Solicitante',
                'verbose_name_plural': 'Cargos de los Solicitantes',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Categoria')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Dependencia')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
            },
        ),
        migrations.CreateModel(
            name='EnfoqueTecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Enfoque')),
            ],
            options={
                'verbose_name': 'Enfoque de la Tecnologia',
                'verbose_name_plural': 'Enfoque de las Tecnologias',
            },
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Estatus')),
            ],
            options={
                'verbose_name': 'Estatus',
                'verbose_name_plural': 'Estatus',
            },
        ),
        migrations.CreateModel(
            name='LenguajeProgramacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Lenguaje')),
            ],
            options={
                'verbose_name': 'Lenguaje de Programacion',
                'verbose_name_plural': 'Lenguajes de Programacion',
            },
        ),
        migrations.CreateModel(
            name='RolResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Rol de Responsable',
                'verbose_name_plural': 'Roles de Responsables',
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.rolresponsable')),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
            },
        ),
        migrations.CreateModel(
            name='SubDependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la SubDependencia')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_dependencias', to='productos.dependencia')),
            ],
            options={
                'verbose_name': 'SubDependencia',
                'verbose_name_plural': 'SubDependencias',
            },
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.cargosolicitante')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitantes', to='productos.dependencia')),
                ('sub_dependencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.subdependencia')),
            ],
            options={
                'verbose_name': 'Solicitante',
                'verbose_name_plural': 'Solicitantes',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('direccion_url', models.URLField()),
                ('fecha_lanzamiento', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.categoria')),
                ('dependencia_usuaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_asignados', to='productos.dependencia')),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.estatus')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.solicitante')),
                ('subdependencia_usuaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.subdependencia')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Tecnologia')),
                ('enfoque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.enfoquetecnologia')),
                ('lenguaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.lenguajeprogramacion')),
            ],
            options={
                'verbose_name': 'Tecnología',
                'verbose_name_plural': 'Tecnologías',
            },
        ),
        migrations.CreateModel(
            name='TrabajoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('frecuencia', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('eventual', 'Eventual')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_operativos', to='productos.producto')),
                ('responsables', models.ManyToManyField(to='productos.responsable')),
            ],
            options={
                'verbose_name': 'Trabajo Operativo',
                'verbose_name_plural': 'Trabajos Operativos',
            },
        ),
        migrations.CreateModel(
            name='ResponsableProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.responsable')),
            ],
            options={
                'verbose_name': 'Responsable del Producto',
                'verbose_name_plural': 'Responsables de los Productos',
                'constraints': [models.UniqueConstraint(fields=('responsable', 'producto'), name='unique_responsable_producto')],
            },
        ),
        migrations.CreateModel(
            name='TecnologiaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('tecnologia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.tecnologia')),
            ],
            options={
                'verbose_name': 'Tecnologia del Producto',
                'verbose_name_plural': 'Tecnologias de los Productos',
                'constraints': [models.UniqueConstraint(fields=('tecnologia', 'producto'), name='unique_tecnologia_producto')],
            },
        ),
    ]
