# Generated by Django 5.1 on 2025-05-02 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_responsable_telefono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('frecuencia', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('eventual', 'Eventual')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_operativos', to='productos.producto')),
                ('responsables', models.ManyToManyField(to='productos.responsable')),
            ],
            options={
                'verbose_name': 'Trabajo Operativo',
                'verbose_name_plural': 'Trabajos Operativos',
            },
        ),
    ]
