# Generated by Django 5.2.1 on 2025-05-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='direccion_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcomponente',
            name='direccion_url',
            field=models.URLField(db_index=True),
        ),
    ]
