# Generated by Django 5.2.1 on 2025-05-17 22:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_tipocomponente_alter_cargosolicitante_nombre_and_more'),
        ('portafolio', '0002_remove_historicalproducto_direccion_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducto',
            name='fecha_lanzamiento',
            field=models.DateField(default=datetime.date(2010, 1, 1)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='dependencia_usuaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos_asignados', to='catalogos.dependencia'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_lanzamiento',
            field=models.DateField(default=datetime.date(2010, 1, 1)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portafolio.solicitante'),
        ),
    ]
