# Generated by Django 5.2.1 on 2025-05-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Componente',
                'verbose_name_plural': 'Tipos de Componentes',
            },
        ),
        migrations.AlterField(
            model_name='cargosolicitante',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del Cargo'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre de la Categoria'),
        ),
        migrations.AlterField(
            model_name='rolresponsable',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre de la Tecnologia'),
        ),
    ]
